# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7709686f188ebd39bbe577ebf26bff0309cf43fe4ed2e914c541d3f92a4b1c7d02ab9ea653f9feac611bd26ee082cfa9da5313f8339a445d295012019b4503d5

test:
  secret_key_base: 8159c52a2861e04caa309b29eebff0fc3a715f8f5f5d5ea6705bbbc3fb461e1ecbf75e11cb2516795bb0c3c43c14da4e922653a3e43a80193ed8cdea009307df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
